### PR TITLE
Create docker-compose.yml

### PR DESCRIPTION
**Pull request by h3ct0rjs**
Hi @LisaHJung ✋🏻 , 

hope you're doing great. Thank you very much for all the effort and the great explanation, I was checking this tutorial today and following it.

I've created this basic docker compose to follow along the tutorial 😃 , this could be a help for others, this docker compose installation implements the following versions : 

- elasticsearch:7.11.1
- kibana:7.11.1

In order to run sucessfully this tutorial you will only need to run : 

`docker-compose up -d `

Best Regards, 
H

### CODE REVIEW

**Comment by LisaHJung** [comment]
Oh wow Héctor(@h3ct0rjs)!!

Thank you so much for putting in the time and effort to create this
supplementary content.

Your email truly made my day and messages like this make me appreciate our
community even more.

This is the first time I've had a community member create a supplementary material for
this course!!

I want to figure out how to best incorporate your work into the page
and also see how your work can be a part of our Elastic Contributor
program.

I will ping some colleagues of mine to see how we could move forward and
keep you posted.

FYI, I am going to be out of office April 28th - May 14th. I really hope we
get this worked out before I leave but in case it doesn't, please know that
I am going to make this a priority first thing when I get back.

Thank you again for your fantastic contribution. You ROCK!!!

Lisa

**Comment by LisaHJung** [comment]
Hey @h3ct0rjs!

Thank you again for your wonderful contribution. I would love to get in touch with you via email to discuss: 
- how you want your contribution to be described in the ReadMe 
- how we can send you swag as a small token of our appreciation

Would you please reach out to me via my email address? 

Thank you!! 

Lisa

**Comment by h3ct0rjs** [comment]
Hi @LisaHJung Wooow that sounds great 😃 
I just sent you an email. 

Also I can create tonight the relevant section for your readme. 

Best Regards, 
H

**Comment by h3ct0rjs** [comment]
Hi @LisaHJung ✋🏻 , 

I also add the readme description per your suggestion. 

Best Regards, 
H

**Comment by LisaHJung** [comment]
@h3ct0rjs ! Thank you so much for your hard work. 

The description looks fantastic. I added minor edits and reorganized it so that the link to your awesome work is included under the Resources tab. 
image

I moved your step by step directions in the docker-compose.yml to keep everything together. 

Thank you again. You are AWESOME!!

**Pull request merged**
